### ISSUE TITLE
Near-alignment of subsurfaces

### ISSUE THREAD

**Issue by brgix** [rd2/tbd#95]
TBD will process OpenStudio subsurfaces (e.g. doors, windows, skylights) to generate _fenestration_-related edges (e.g. heads, jambs, sills) as linear thermal bridges. Whenever individual subsurfaces share common edges (e.g. side-by-side windows, true corner windows or corner curtainwall vision sections), TBD ignores such common edges - the presumption is that these are similar to fenestration _dividers_ - the derating effect of which is already factored in overall fenestration U-factor calculations/testing. Our general recommendation to modellers (when applicable): align model subsurfaces (along shared edges) - e.g. avoid leaving a 25-mm band between subsurfaces. Why not? TBD would label 2x nearly-aligned subsurface edges as 2x window _jambs_ (for instance), when in reality there are likely none. TBD would in turn _thermally_ derate parent surfaces (e.g. a host wall), when in fact it shouldn't. A similar situation occurs when subsurfaces are near (yet not aligned) with parent surface edges. While we consider this as bad input, we do recognize that many third-party packages generate such cases behind the scenes, that there are legacy models in circulation, etc. We suggest introducing a subsurface edge tolerance (e.g. 50 mm), whereby nearly-aligned subsurfaces (or near-corner subsurfaces) aren't unduly generating derating processes. Some may argue 100 mm is a more suitable threshold. In progress ...

**Comment by macumber** [comment]
I briefly looked through the TBD guide and I didn't see a section on sub surfaces, I would suggest adding one if it doesn't already exist.  Sub surface vertices should include the outer frame so I think two sub surfaces would have to be at least a 2'x4' apart (or two). I think this is where your 50 mm and 100 mm limits come from so both those limits make sense to me.

**Comment by brgix** [comment]
Completely agree. The Guide will be updated once the preferred solution is merged and TBD re-released.
